apiVersion: v1
kind: Pod
metadata:
  name: disco
  namespace: tenant-mobilecoin-imogen
spec:
  containers:
  - name: disco
    image: technillogue/personality-clip:0.0.2
    # command: ["/usr/bin/sleep"]
    # args: ["1h"]
    resources:
      limits:
        cpu: 1
        memory: 4Gi #idk if it needs this much
        nvidia.com/gpu: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu.nvidia.com/class
            operator: In
            values:
              - Tesla_V100_PCIE
              - Tesla_V100_NVLINK
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 20
          preference:
            matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - Tesla_V100_PCIE
